<?php
	$arrPrevYear=$this->prevYear;
	$arrCurrentYear=$this->currentYear;
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
	  google.load("visualization", "1", {packages:["corechart"]});

      google.setOnLoadCallback(drawCurrentYear);

      function drawCurrentYear() {
        var data = google.visualization.arrayToDataTable(
        		<?php
        			$arrMounth=array(0,"January","February","March","April","May","June","July","August","September","October","November","December");
					$html="[";
        			$html.="['Mounth'";
	        		foreach ($arrCurrentYear as $strGroupName => $arrItem){
	        			$html.=",'".$strGroupName."'";
	        		}
	        		$html.="]";

	        		for ($countM=1; $countM<$this->intCurrentMounth;$countM++){
	        			$html.=",['".$arrMounth[$countM]."'";
	        			foreach ($arrCurrentYear as $strGroupName => $arrTable){
	        				if (!empty($arrTable[str_pad($countM, 2, "0", STR_PAD_LEFT)])){
	        					$html.=",".$arrTable[str_pad($countM, 2, "0", STR_PAD_LEFT)];
	        				}else{
	        					$html.=",0";
	        				}
	        			}
	        			$html.="]";
	        		}
	        		$html.="]";
	        		echo $html;
        		?>

                );

        var options = {
          title: '<?php echo $this->translate("LBL_NUMBER_LOCKS_BY_GROUP_IN")." ".$this->strCurrentYear;?>',
          vAxis: {title: '',  titleTextStyle: {color: 'red'}},
          width: '100%',
          chartArea: {left:38,top:30, width:"75%",height:"70%"},
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_<?php echo $this->strCurrentYear?>'));
        chart.draw(data, options);
      }
</script>
<div id="chart_<?php echo $this->strCurrentYear?>" style="width: 1250px; height: 500px;"></div>
<?php if (!empty($arrPrevYear)){?>
	<script type="text/javascript">

	function drawPrevYear() {
        var data = google.visualization.arrayToDataTable(
        		<?php
        			$arrMounth=array(0,"January","February","March","April","May","June","July","August","September","October","November","December");
					$html="[";
        			$html.="['Mounth'";
	        		foreach ($arrPrevYear as $strGroupName => $arrItem){
	        			$html.=",'".$strGroupName."'";
	        		}
	        		$html.="]";

	        		for ($countM=1; $countM<13;$countM++){
	        			$html.=",['".$arrMounth[$countM]."'";
	        			foreach ($arrPrevYear as $strGroupName => $arrTable){
	        				if (!empty($arrTable[str_pad($countM, 2, "0", STR_PAD_LEFT)])){
	        					$html.=",".$arrTable[str_pad($countM, 2, "0", STR_PAD_LEFT)];
	        				}else{
	        					$html.=",0";
	        				}
	        			}
	        			$html.="]";
	        		}
	        		$html.="]";
	        		echo $html;
        		?>

                );

        var options = {
          title: '<?php echo $this->translate("LBL_NUMBER_LOCKS_BY_GROUP_IN")." ".$this->strPrevYear;?>',
          vAxis: {title: '',  titleTextStyle: {color: 'red'}},
          width: '100%',
          chartArea: {left:38,top:30, width:"75%",height:"70%"},
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_<?php echo $this->strPrevYear?>'));
        chart.draw(data, options);
      }

	  google.setOnLoadCallback(drawPrevYear);
	</script>
	<br>
<div id="chart_<?php echo $this->strPrevYear?>" style="width: 1250px; height: 500px;"></div>
<?php }?>
