<?php
return array (
  0 =>
  array (
    'id_menu' => '29',
    'code' => 'roles',
    'label' => 'LBL_ROLES',
    'id_parent' => '27',
    'uri' => '',
    'col_module' => 'user',
    'col_controller' => 'roles',
    'col_action' => 'index',
    'css_class' => '',
    'id_resources' => '34',
    'privelege' => 'index',
    'sort_order' => '99',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:25:11',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:25:11',
    'is_deleted' => '0',
  ),
  1 =>
  array (
    'id_menu' => '30',
    'code' => 'assertion',
    'label' => 'LBL_ASSERTION',
    'id_parent' => '27',
    'uri' => '',
    'col_module' => 'user',
    'col_controller' => 'assertion',
    'col_action' => 'index',
    'css_class' => '',
    'id_resources' => '33',
    'privelege' => 'index',
    'sort_order' => '99',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:24:42',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:24:42',
    'is_deleted' => '0',
  ),
  2 =>
  array (
    'id_menu' => '28',
    'code' => 'resources',
    'label' => 'LBL_RESOURCES',
    'id_parent' => '27',
    'uri' => '',
    'col_module' => 'user',
    'col_controller' => 'resources',
    'col_action' => 'index',
    'css_class' => '',
    'id_resources' => '35',
    'privelege' => 'index',
    'sort_order' => '99',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:25:36',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:25:36',
    'is_deleted' => '0',
  ),
  3 =>
  array (
    'id_menu' => '27',
    'code' => 'acl',
    'label' => 'LBL_ACL',
    'id_parent' => '24',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '37',
    'privelege' => 'index',
    'sort_order' => '99',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:26:03',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:26:03',
    'is_deleted' => '0',
  ),
  4 =>
  array (
    'id_menu' => '26',
    'code' => 'label',
    'label' => 'LBL_LABEL',
    'id_parent' => '16',
    'uri' => '',
    'col_module' => 'labels',
    'col_controller' => 'index',
    'col_action' => 'index',
    'css_class' => '',
    'id_resources' => '28',
    'privelege' => '',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:26:39',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:26:39',
    'is_deleted' => '0',
  ),
  5 =>
  array (
    'id_menu' => '24',
    'code' => 'config',
    'label' => 'LBL_CONFIG',
    'id_parent' => '16',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:27:13',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:27:13',
    'is_deleted' => '0',
  ),
  6 =>
  array (
    'id_menu' => '25',
    'code' => 'menu',
    'label' => 'LBL_MENU',
    'id_parent' => '24',
    'uri' => '',
    'col_module' => 'menu',
    'col_controller' => 'index',
    'col_action' => 'index',
    'css_class' => '',
    'id_resources' => '29',
    'privelege' => 'index',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:27:06',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:27:06',
    'is_deleted' => '0',
  ),
  7 =>
  array (
    'id_menu' => '23',
    'code' => 'external',
    'label' => 'LBL_EXTERNAM',
    'id_parent' => '16',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:27:10',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:27:10',
    'is_deleted' => '0',
  ),
  8 =>
  array (
    'id_menu' => '22',
    'code' => 'groups',
    'label' => 'LBL_GROUPS',
    'id_parent' => '19',
    'uri' => '',
    'col_module' => 'system',
    'col_controller' => 'enums',
    'col_action' => 'groups',
    'css_class' => '',
    'id_resources' => '38',
    'privelege' => 'groups',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:51:06',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:51:06',
    'is_deleted' => '0',
  ),
  9 =>
  array (
    'id_menu' => '21',
    'code' => 'sites',
    'label' => 'LBL_SITES',
    'id_parent' => '19',
    'uri' => '',
    'col_module' => 'system',
    'col_controller' => 'enums',
    'col_action' => 'sites',
    'css_class' => '',
    'id_resources' => '38',
    'privelege' => 'sites',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:51:11',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:51:11',
    'is_deleted' => '0',
  ),
  10 =>
  array (
    'id_menu' => '20',
    'code' => 'entitytypes',
    'label' => 'LBL_ENT_TYPES',
    'id_parent' => '176',
    'uri' => '',
    'col_module' => 'eav',
    'col_controller' => 'index',
    'col_action' => 'entity-types',
    'css_class' => '',
    'id_resources' => '39',
    'privelege' => 'entityTypes',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-15 10:00:39',
    'updated_by' => '0',
    'updated_on' => '2011-11-15 10:00:39',
    'is_deleted' => '0',
  ),
  11 =>
  array (
    'id_menu' => '19',
    'code' => 'statics',
    'label' => 'LBL_STATICS',
    'id_parent' => '16',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:51:20',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:51:20',
    'is_deleted' => '0',
  ),
  12 =>
  array (
    'id_menu' => '18',
    'code' => 'logs',
    'label' => 'Logs',
    'id_parent' => '0',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '40',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:51:23',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:51:23',
    'is_deleted' => '0',
  ),
  13 =>
  array (
    'id_menu' => '17',
    'code' => 'events',
    'label' => 'Events',
    'id_parent' => '0',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '30',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:51:25',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:51:25',
    'is_deleted' => '0',
  ),
  14 =>
  array (
    'id_menu' => '16',
    'code' => 'system',
    'label' => 'LBL_SYSTEM',
    'id_parent' => '0',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '99',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:51:34',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:51:34',
    'is_deleted' => '0',
  ),
  15 =>
  array (
    'id_menu' => '15',
    'code' => 'users',
    'label' => 'LBL_USERS',
    'id_parent' => '0',
    'uri' => '',
    'col_module' => 'user',
    'col_controller' => 'index',
    'col_action' => 'index',
    'css_class' => '',
    'id_resources' => '31',
    'privelege' => 'index',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:51:48',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:51:48',
    'is_deleted' => '0',
  ),
  16 =>
  array (
    'id_menu' => '14',
    'code' => 'catalog',
    'label' => 'LBL_CATALOG',
    'id_parent' => '0',
    'uri' => '',
    'col_module' => 'catalog',
    'col_controller' => 'index',
    'col_action' => 'index',
    'css_class' => '',
    'id_resources' => '25',
    'privelege' => 'index',
    'sort_order' => '20',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:51:55',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:51:55',
    'is_deleted' => '0',
  ),
  17 =>
  array (
    'id_menu' => '13',
    'code' => 'locks',
    'label' => 'LBL_LOCKS',
    'id_parent' => '0',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '10',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:52:00',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:52:00',
    'is_deleted' => '0',
  ),
  18 =>
  array (
    'id_menu' => '12',
    'code' => 'code',
    'label' => 'lbl',
    'id_parent' => '0',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-03 13:18:12',
    'updated_by' => '0',
    'updated_on' => '2011-01-01 00:00:00',
    'is_deleted' => '1',
  ),
  19 =>
  array (
    'id_menu' => '175',
    'code' => 'authorization',
    'label' => 'LBL_AUTH',
    'id_parent' => '27',
    'uri' => '',
    'col_module' => 'user',
    'col_controller' => 'authorization',
    'col_action' => 'index',
    'css_class' => '',
    'id_resources' => '37',
    'privelege' => 'index',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-10 10:52:04',
    'updated_by' => '0',
    'updated_on' => '2011-11-10 10:52:04',
    'is_deleted' => '0',
  ),
  20 =>
  array (
    'id_menu' => '176',
    'code' => 'eav',
    'label' => 'LBL_EAV',
    'id_parent' => '16',
    'uri' => '#',
    'col_module' => '',
    'col_controller' => '',
    'col_action' => '',
    'css_class' => '',
    'id_resources' => '0',
    'privelege' => '',
    'sort_order' => '0',
    'created_by' => '0',
    'created_on' => '2011-11-14 11:40:10',
    'updated_by' => NULL,
    'updated_on' => NULL,
    'is_deleted' => '0',
  ),
);
