<?php
//Labadmin_Models_Static::sendJgrowlMessages ( $this );
echo $this->doctype (Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL);
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php
		include "header.phtml";
		?>
	</head>
	<body>
		<div class="main">
			<div class="header">
				<a href="/" class="logo"><img src="/images/Mellanox_logo.png" alt="BF" title="BF" /></a>
				<div class="title">
					QSTAT
					<?php
					if (defined('APPLICATION_ENV') && 'production' != APPLICATION_ENV) {
						echo '<br />'.APPLICATION_ENV;
					}
					?>
				</div>
				<div class="status">
					<?php
					$auth = Zend_Auth::getInstance();
					if ($auth->hasIdentity()) {
						$session = new Zend_Session_Namespace("user");
						$arrUserData = $session->userDetails;
						?>
						Welcome, <strong><?php echo $arrUserData->{User_Model_Db_Users::COL_FIRST_NAME}.' '.$arrUserData->{User_Model_Db_Users::COL_LAST_NAME};?></strong> &nbsp;|&nbsp; <a href="<?php echo $this->url(
							array('module' => 'user', 'controller' => 'authentication', 'action' => 'logout'),
							null, true, false);?>">LogOut</a>
						<?php
					} else {
						?>
						<strong>Welcome to QSTAT</strong> &nbsp;|&nbsp; <a href="<?php echo $this->url(
							array('module' => 'user', 'controller' => 'authentication', 'action' => 'login'),
							null, true, false);?>">LogIn</a>
						<?php
					}
					?>
				</div>
				<br class="clear" />
			</div>

			<div class="menu_top">
				<?php echo $this->navigation()->menu(); ?>
				<br class="clear" />
			</div>

			<div class="main_top_left">
				<div class="main_top_right">
					<div class="tabs">
						<?php echo $this->navigation()->menu()->setMaxDepth(10)->setOnlyActiveBranch(true)->setRenderParents(false)->setMinDepth(1); ?>
						<br class="clear" />
					</div>
				</div>
			</div>
			<!--// End HEADER-->

			<!--// Start CONTENT-->
			<div class="content_left">
				<div class="content_right">
					<div class="content">
						<div class="title">
							<h1><?php echo $this->navigation()->breadcrumbs()->setSeparator('&nbsp;/&nbsp;')->setMinDepth(0); ?></h1>
							<div class="date"><?php echo date("d/m/Y");?></div>
							<hr />
						</div>
						<?php echo $this->layout()->content; ?>
					</div>
				</div>
			</div>
			<!--// End CONTENT-->

			<div class="content_footer_left">
				<div class="content_footer_right">
					<div class="content_footer"></div>
				</div>
			</div>

			<!--// Start FOOTER-->
			<script>
				function NASort(a, b) {
					if (a.innerHTML == 'NA') {
						return 1;
					}
					else if (b.innerHTML == 'NA') {
						return -1;
					}
					return (a.innerHTML > b.innerHTML) ? 1 : -1;
				};

				$('select').each(function( index ) {
					// $(this).find('option').sort(NASort).appendTo($(this));
				});
			</script>
			<div class="footer">
				<strong>
					Mellanox
				</strong>
				&copy; <?php echo date("Y"); ?>
			</div>
		</div>
	</body>
</html>